#! /usr/bin/perl

# compare_dot_files - compare the dot files with the files here, list
#                     changed files and their changes

use File::Compare;
use File::Find;

if ($ARGV[0] eq '-d') {
    $do_diff++;
}

sub map_file {
    my $ufile = shift;
    my $dfile = $ufile;
    $dfile =~ s/^_/./;
    $dfile = $ENV{HOME} . '/' . $dfile;
    return $dfile;
}

find({ wanted => sub { -f $_ and push(@files, $_); },
       no_chdir => 1,}, <_*>);

foreach $ufile (@files) {
    $ufile =~ s,^\./,,;
    $dfile = $ufile; $dfile =~ s,^_,.,;
    $dfile = $ENV{HOME} . '/' . $dfile;

    if (not -e $dfile) {
        print "$dfile doesn't exist\n";
    } elsif (compare($dfile, $ufile)) {
        if (-M $dfile < -M $ufile) {
            $newer = "newer";
        } else {
            $newer = "older";
        }
        print "$dfile is $newer than $ufile\n";
    }
}
