; jive.el - Tim Gates 1988
;
; minor mode for automatic jive
; abbrev-mode using jive-abbrev-table

(defun jive nil "Jive abbrev mode, Uses jive-abbrev-table"
  (interactive)
  (abbrev-mode 1)
  (setq local-abbrev-table jive-abbrev-table)
  (message "Jive Mode ON")
)

(define-abbrev-table 'jive-abbrev-table '(
    ("a" "some" nil 0 )
    ("almost" "mos'" nil 0 )
    ("alright" "coo'" nil 0 )
    ("amateur" "begina'" nil 0 )
    ("aren't" "ain't" nil 0 )
    ("ask" "ax'" nil 0 )
    ("atlas" "Isaac" nil 0 )
    ("bad" "bad-ass" nil 0 )
    ("basket" "hoop" nil 0 )
    ("beat" "whup'" nil 0 )
    ("because" "a'cuz" nil 0 )
    ("believe" "recon'" nil 0 )
    ("big" "big-ass" nil 0 )
    ("black" "brother" nil 0 )
    ("bob" "Liva' Lips" nil 0 )
    ("book" "scribblin'" nil 0 )
    ("boss" "Main Man" nil 0 )
    ("break" "boogie" nil 0 )
    ("broken" "bugger'd" nil 0 )
    ("buy" "steal" nil 0 )
    ("can" "kin" nil 0 )
    ("car" "wheels" nil 0 )
    ("come" "mosey on down" nil 0 )
    ("computer" "clunker" nil 0 )
    ("dance" "boogy" nil 0 )
    ("david" "Issac" nil 0 )
    ("dead" "wasted" nil 0 )
    ("detroit" "Mo-town" nil 0 )
    ("did" "dun did" nil 0 )
    ("does" "duz" nil 0 )
    ("don't" "duzn't" nil 0 )
    ("down" "waaay down" nil 0 )
    ("drive" "roll" nil 0 )
    ("eat" "feed da bud" nil 0 )
    ("er" "a'" nil 0 )
    ("ex" "'es" nil 0 )
    ("exc" "'s" nil 0 )
    ("exp" "'sp" nil 0 )
    ("exs" "'s" nil 0 )
    ("file" "stash" nil 0 )
    ("first" "fust" nil 0 )
    ("fool" "honkyfool" nil 0 )
    ("football" "ball" nil 0 )
    ("four" "foe" nil 0 )
    ("friend" "homey" nil 0 )
    ("from" "fum" nil 0 )
    ("get" "git" nil 0 )
    ("girl" "goat" nil 0 )
    ("good" "baaaad" nil 0 )
    ("got" "gots" nil 0 )
    ("government" "guv'ment" nil 0 )
    ("hair" "fro" nil 0 )
    ("has" "gots'ta" nil 0 )
    ("hat" "fedora" nil 0 )
    ("have" "gots'" nil 0 )
    ("have to" "gots'ta" nil 0 )
    ("haven't" "aint" nil 0 )
    ("head" "'haid" nil 0 )
    ("Hi" "'Sup, dude" nil 0 )
    ("home" "plantation" nil 0 )
    ("house" "crib" nil 0 )
    ("I" "ah'" nil 0 )
    ("Indianapolis" "Nap-town" nil 0 )
    ("injured" "hosed" nil 0 )
    ("is" "be" nil 0 )
    ("italian" "greaser" nil 0 )
    ("jack" "Buckwheat" nil 0 )
    ("jim" "Bo-Jangles" nil 0 )
    ("jive" "JIBE" nil 0 )
    ("joe" "Massa'" nil 0 )
    ("john" "Raz'tus" nil 0 )
    ("joseph" "Massa'" nil 0 )
    ("just" "plum" nil 0 )
    ("killed" "wasted" nil 0 )
    ("knew" "knowed" nil 0 )
    ("known" "knode" nil 0 )
    ("larry" "Remus" nil 0 )
    ("lie" "honky jibe" nil 0 )
    ("like" "likes" nil 0 )
    ("magazine" "issue of GQ" nil 0 )
    ("man" "dude" nil 0 )
    ("mark" "Amos" nil 0 )
    ("mary" "Snow Flake" nil 0 )
    ("men" "dudes" nil 0 )
    ("mens" "dudes" nil 0 )
    ("meta" "meta-freakin'" nil 0 )
    ("mexican" "wet-back" nil 0 )
    ("modem" "doodad" nil 0 )
    ("mohammed" "liva' lips" nil 0 )
    ("money" "bre'd" nil 0 )
    ("music" "beat" nil 0 )
    ("my" "mah'" nil 0 )
    ("name" "dojigger" nil 0 )
    ("negro" "brother" nil 0 )
    ("nice" "supa' fine" nil 0 )
    ("nigger" "gentleman" nil 0 )
    ("oar" "o'" nil 0 )
    ("of" "uh" nil 0 )
    ("okay" "coo'" nil 0 )
    ("open" "jimmey" nil 0 )
    ("opened" "jimmey'd" nil 0 )
    ("or" "o'" nil 0 )
    ("paper" "sheet" nil 0 )
    ("path" "alley" nil 0 )
    ("paul" "Fuh'rina" nil 0 )
    ("people" "sucka's" nil 0 )
    ("per" "puh'" nil 0 )
    ("person" "sucka'" nil 0 )
    ("phil" "dat fine soul" nil 0 )
    ("police" "honky pigs" nil 0 )
    ("pontiff" "wiz'" nil 0 )
    ("pope" "wiz'" nil 0 )
    ("pravda" "dat commie rag" nil 0 )
    ("president" "super-dude" nil 0 )
    ("prime minister" "super honcho" nil 0 )
    ("program" "honky code" nil 0 )
    ("radio" "transista'" nil 0 )
    ("read" "eyeball" nil 0 )
    ("reagan" "Kingfish" nil 0 )
    ("robert" "Leroy" nil 0 )
    ("ronald" "Rolo" nil 0 )
    ("sandy" "dat fine femahnaine ladee" nil 0 )
    ("school" "farm" nil 0 )
    ("send" "t'row" nil 0 )
    ("shoe" "kicker" nil 0 )
    ("small" "little-ass" nil 0 )
    ("so" "so's" nil 0 )
    ("something" "sump'n" nil 0 )
    ("strange" "funky" nil 0 )
    ("string" "chittlin'" nil 0 )
    ("sure" "sho' nuff" nil 0 )
    ("take" "snatch" nil 0 )
    ("takes" "snatch'd" nil 0 )
    ("talk" "rap" nil 0 )
    ("the" "da damn" nil 0 )
    ("thing" "wahtahmellun" nil 0 )
    ("understand" "dig it" nil 0 )
    ("UNIX" "that slow mo-fo" nil 0 )
    ("unix" "slow mo-fo" nil 0 )
    ("VAX" "pink Cadillac" nil 0 )
    ("very" "real" nil 0 )
    ("want" "wants'" nil 0 )
    ("was" "wuz" nil 0 )
    ("water" "booze" nil 0 )
    ("Well" "Sheeit" nil 0 )
    ("well" "sheeit" nil 0 )
    ("were" "wuz" nil 0 )
    ("what" "whut" nil 0 )
    ("white" "honky" nil 0 )
    ("wife" "mama" nil 0 )
    ("will" "gots'ta" nil 0 )
    ("with" "wit'" nil 0 )
    ("woman" "mama" nil 0 )
    ("women" "honky chicks" nil 0 )
    ("write" "scribble" nil 0 )
    ("you" "ya'" nil 0 )
    ("young" "yung" nil 0 )
    ("your" "yo'" nil 0 )
    ("you're" "youse" nil 0 )
))
